name: 'Named Branches'
on:
  push:
  pull_request:
jobs:
  named-branches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1000
    - uses: Julian/named-branch-action@v1
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
