name: 'Named Branches'
on: push
jobs:
  named-branches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: Julian/named-branch-action@v0.3.0
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
